from enum import StrEnum


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    DEFERRED = "DEFERRED"


class PlanningStatus(StrEnum):
    PLANNED = "PLANNED"
    DEFERRED = "DEFERRED"


class SolverStatus(StrEnum):
    OPTIMAL = "OPTIMAL"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    TIME_LIMIT = "TIME_LIMIT"
    ERROR = "ERROR"


class DeferredReason(StrEnum):
    ORDER_EXCEEDS_ALL_VEHICLE_CAPACITIES = "ORDER_EXCEEDS_ALL_VEHICLE_CAPACITIES"
    INSUFFICIENT_TOTAL_CAPACITY = "INSUFFICIENT_TOTAL_CAPACITY"
    SHIFT_TIME_INFEASIBLE = "SHIFT_TIME_INFEASIBLE"
    NO_ACTIVE_VEHICLE = "NO_ACTIVE_VEHICLE"
    SOLVER_DROPPED_WITH_PENALTY = "SOLVER_DROPPED_WITH_PENALTY"
    SOLVER_TIMEOUT_NO_FEASIBLE_ASSIGNMENT = "SOLVER_TIMEOUT_NO_FEASIBLE_ASSIGNMENT"
    INVALID_ORDER = "INVALID_ORDER"
